// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krtgeqejpsdyzuesopez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtydGdlcWVqcHNkeXp1ZXNvcGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDIwOTksImV4cCI6MjA2MzkxODA5OX0.IMp_uuvTw_UtcDtCip3qsObsnt0z2sz8fJEQJ8sMuew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);